### ISSUE TITLE
Add e2e tests for external health monitor controller

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-health-monitor#34]

**Comment by NickrenREN** [comment]
Anyone who is interested in this ?

**Comment by irbekrm** [comment]
Hi! I would be interested in working on this issue.

**Comment by NickrenREN** [comment]
Thanks @irbekrm

**Comment by irbekrm** [comment]
I was also wondering what driver should be used for the e2e tests. 
I see [here](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1432-volume-health-monitor#e2e-tests) that the e2e tests should use hostpath CSI driver and GCE PD driver, however I looked at the hostpath CSI driver and it does not implement the required interface.
Is the requirement to use hostpath CSI driver and GCE PD driver still up to date?

**Comment by xing-yang** [comment]
We can use the CSI hostpath driver for e2e tests.

@fengzixu is working on the following issue to add health monitoring support in the CSI hostpath driver.  So these e2e tests tasks are actually depending on this one.
https://github.com/kubernetes-csi/external-health-monitor/issues/21

For GCE PD driver, I think we'll have to wait until it has the health monitoring support.

**Comment by xing-yang** [comment]
Hi @irbekrm,
In addition to adding e2e tests using the CSI hostpath driver, we should also add e2e tests using the CSI Mock Driver.  The advantage of using the mock driver is that we can also inject failure using the javascript hooks.  See the following links for details.  Can you take a look of this?
* Javascript hooks for csi mock driver: https://github.com/kubernetes-csi/csi-test/pull/251
* e2e test example: https://github.com/kubernetes/kubernetes/commit/a4f080861f3586aae0f235e914526807eeea5cfa

**Comment by irbekrm** [comment]
Hi @xing-yang ,

Thank you! I will take a look at the example and start working on this. I might get back with some questions about the approach.

**Comment by irbekrm** [comment]
Actually, I am having some doubts about the e2e tests for this with the CSI Mock Driver and the javascript hooks.

The external health monitor creates a `VolumeConditionAbnormal` event only if volume condition is marked as `abnormal:true` in the gRPC response from the driver. But with the hooks, it is only possible to return with a gRPC error code and empty gRPC response, so I cannot force the mock driver to return a gRPC response with `abnormal:true` via a hook.

I was also looking at using the hooks to return early from one of the CSI Mock Driver methods that actually create the volume, so that the condition 'becomes' abnormal in the driver itself. But because the hooks can only cause the driver method to return with a non-OK gRPC code, I think this is also not possible because the volume creation would just fail.

So, I am not sure if the creation of `VolumeConditionAbnormal` and `VolumeConditionNormal` events can be e2e-tested with the CSI Mock Driver? Maybe I could just wait for this PR https://github.com/kubernetes-csi/csi-driver-host-path/pull/210 to be merged and test with the CSI hostpath driver?

**Comment by xing-yang** [comment]
I see.  Let's wait for the CSI hostpath driver implementation then.

**Comment by fengzixu** [comment]
@irbekrm Hi. Long time no see. How are you? Actually, I want to tell you the `CSI hostpath driver implementation is already finished. I think you can start to work on e2e test issue from now.

**Comment by irbekrm** [comment]
Hi! Thanks for letting me know- I will take a look this weekend 😄

**Comment by xing-yang** [comment]
@irbekrm Not sure if you have started working on this.  Actually right now there's no good way of writing an e2e test for this feature.  This is because that we are only reporting events to PVCs.  Events can disappear so it is not reliable to write an e2e test to verify if an event is recorded.

**Comment by irbekrm** [comment]
Hi, thank you for letting me know- actually I had not started working on this properly.

I think I will then better unassign myself- perhaps someone else can take a look or maybe there will be a better way to test this sometime in the future!

/unassign

**Comment by xing-yang** [comment]
Closing this as we are not adding e2e tests for now.
