### ISSUE TITLE
Send recovery events when volumes back to health

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes-csi/external-health-monitor#8]
When volumes recover from unhealthy condition, check if abnormal events are sent, if so, send recovery events to indicate the volumes are healthy now.

**Comment by fengzixu** [comment]
@NickrenREN @xing-yang Is the issue approved? If the mock-driver issue has been finished, I want to take it

**Comment by NickrenREN** [comment]
@fengzixu I think we need this

**Comment by fengzixu** [comment]
About the implementation of this issue, my thought is below

1. Construct the indexer of event cache based on event.ObjectReference.UID
2. When pv checker checked volume, if the volume is healthy,  try to get AbnormalVolumeEvent from cache by event.ObjectReference.UID. If we found it, send the recovery event. Otherwise, do nothing.

But, the event was stored in etcd for an hour, it was decided by `event-ttl` argument of kube-apiserver.

**Comment by fengzixu** [comment]
@xing-yang @NickrenREN  Could you check my comment above ^

**Comment by NickrenREN** [comment]
@fengzixu Sending events is what we do at the first stage since it is the easiest way to achieve.
At the first stage, i think we still need to send recovery events if the volume becomes healthy again during the period of `event-ttl`.  In the meanwhile, if the volume is still unhealthy after `event-ttl`, we need to send  Abnormal events again.
Anyway, in the next stage, i think we need to find a better way to indicate the unhealthy condition.

**Comment by NickrenREN** [comment]
I am ok about the cache implementation. As you said, we need to take `event-ttl` into account.

**Comment by fengzixu** [comment]
But. there still is a timing issue

1. abnormal volume event was expired due to `event-ttl`. And external-healthy-monitor controller/agent was in waiting state within interval time. In that time, the volume may come back to the healthy state.
2. external-healthy-monitor cannot find the abnormal volume event. Should it send the recovery event? Ideally, it shouldn't I think

**Comment by NickrenREN** [comment]
>external-healthy-monitor cannot find the abnormal volume event. Should it send the recovery event?

NO, as I said in the comment above, recovery events should only be send during the period of `event-ttl`

**Comment by xing-yang** [comment]
We have discussed about this in Yesterday's CSI meeting and decided we are not going to do this for v1.19 release.  We can take a look in the future after 1.19 (maybe implement an internal cache to keep track of the events).

**Comment by NickrenREN** [comment]
I am not saying we want this in 1.19.  Just want to clarify we need this.
And 1.19 should not block this discussion

**Comment by fengzixu** [comment]
> I am not saying we want this in 1.19. Just want to clarify we need this.
> And 1.19 should not block this discussion

Yep. I got your mean
